name: Deploy to DeployGate

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # google-service.jsonをデコードする
      # see:https://qiita.com/sudo5in5k/items/5b6da5dbba3fc2514319
      - name: decode google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Build app
        run: ./gradlew assemble

      - name: Deploy to DeployGate
        run: ./gradlew uploadDeployGateDebug
        env:
          DEPLOYGATE_API_TOKEN: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          DEPLOYGATE_APP_OWNER_NAME: ${{ secrets.DEPLOYGATE_APP_OWNER_NAME }}
